version: "3"

services:
  host-db:
    image: mongo
    restart: always
    container_name: mongo-db
    ports:
      - 27017:27017
  host-app:
    image: ${USER}/stellato:1.0.0-SNAPSHOT
    restart: always
    container_name: stellato-app
    depends_on:
      - host-db
    ports:
      - 8080:8080
      - 5005:5005